_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  TEXTFUSENET_MUTIL_PATH_FUSE_ON: True
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  PIXEL_STD: [19.48, 19.48, 19.48]
  # PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    # NUM_GROUPS: 32
    # WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    # NMS_THRESH_TEST: 0.4
    NMS_THRESH_TEST: 0.3
  TEXTFUSENET_SEG_HEAD:
    FPN_FEATURES_FUSED_LEVEL: 1
    POOLER_SCALES: (0.125,)
    # FPN_FEATURES_FUSED_LEVEL: 2
    # POOLER_SCALES: (0.0625,)
    
DATASETS:
  # TRAIN: ("synthtext_texgen_train",) 
  # TRAIN: ("synthtext_texgen_train","synthtext_gb_highres")   
  TRAIN: ("coco_data_01_char__lines_test_250", "coco_data1400x1400", "coco_data_01_char_lines_train_1k", "coco_data_01_char_large_train_250","coco_data_02_char_test_250", "coco_data_01_char_train", "coco_data_01_char_train_1000", "coco_data_02_char_train_250", )   
  TEST: ( "coco_data_01_char_train_500", "coco_data512x512")  


SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  STEPS: (100000, 200000, )
  MAX_ITER: 500000
  CHECKPOINT_PERIOD: 500

# -----------------------------------------------------------------------------

# INPUT:
#   # Size of the smallest side of the image during training 
#   MIN_SIZE_TRAIN: (800,900,1000,1200,1300)
#   # Maximum size of the side of the image during training
#   MAX_SIZE_TRAIN: 1400
#   # Size of the smallest side of the image during testing. Set to zero to disable resize in testing.
#   MIN_SIZE_TEST: 0
#   # Maximum size of the side of the image during testing
#   MAX_SIZE_TEST: 1400

# INPUT:
#   MIN_SIZE_TRAIN: (800,1000,1200)
#   MAX_SIZE_TRAIN: 1500
#   MIN_SIZE_TEST: 800
#   MAX_SIZE_TEST: 1500

INPUT:
  MIN_SIZE_TRAIN: (512, 800,1000,1200)
  MAX_SIZE_TRAIN: 1400
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 1400


TEST:
  DETECTIONS_PER_IMAGE : 2000


OUTPUT_DIR: "./out_dir_r101/pre_model/"

